#!/usr/bin/env python3
"""Compute ContextLens metrics from the database only — no invented values.

Delegates aggregation to ``app.metrics.aggregate``. Outputs Markdown for
``PROJECT_METRICS.md`` (ContextLens section).

Heuristic vs LLM judge metrics are reported in **separate sections** (no blended score averages).

Usage (from ``backend/``)::

    python scripts/generate_contextlens_metrics.py
    python scripts/generate_contextlens_metrics.py --format markdown
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

_BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(_BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(_BACKEND_ROOT))

from app.database import engine  # noqa: E402
from app.metrics.aggregate import aggregate_all_metrics  # noqa: E402


def _fmt_num(v: Any) -> str:
    if v is None:
        return "not available"
    if isinstance(v, Decimal):
        return f"{float(v):.6f}".rstrip("0").rstrip(".")
    if isinstance(v, float):
        return f"{v:.6f}".rstrip("0").rstrip(".")
    return str(int(v) if v == int(v) else v)


def render_project_metrics_markdown(m: dict[str, Any]) -> str:
    today = datetime.now(UTC).date().isoformat()
    lines = [
        "<!-- Generated by backend/scripts/generate_contextlens_metrics.py -->",
        f"<!-- UTC date: {today} -->",
        "",
        "## ContextLens (generated metrics)",
        "",
        f"Last updated: {today}",
        "",
        "### Semantics (read first)",
        "- **N/A vs zero:** In this report, **“not available”** means the value is **undefined or omitted** (Python `None` / SQL `NULL` semantics), **not** the number zero.",
        "  - **Averages** (scores, latencies, cost averages): if no rows supply non-NULL data for that metric → **not available** (we do **not** print `0` as a fake average).",
        "  - **Counts** (`benchmark_datasets`, `evaluation_rows_*`, `configs_tested`, …): **`0` is a real count** when the table or filter has no rows.",
        "  - **`llm_judge_call_rate`**: **not available** when there are **zero** `evaluation_results` rows (denominator 0). If rows exist and none used the LLM judge, the rate is **`0`** (honest zero).",
        "- **total_traced_runs**: runs with ≥1 `retrieval_results` AND ≥1 `evaluation_results` (any evaluator).",
        "- **total_traced_runs_heuristic** / **total_traced_runs_llm**: same, filtered by evaluation row bucket (see `app/domain/evaluator_bucket.py`).",
        "- **Score averages** (`avg_*_heuristic` / `avg_*_llm`): **never blended**; each AVG uses only rows in that bucket.",
        "- **`cost_usd` (stored):** on full RAG, **generation + judge** token estimates are summed (`app/services/full_rag_evaluation.py`). If **pricing is disabled** (both `ANTHROPIC_*_USD_PER_MILLION_TOKENS` ≤ 0) or usage is unknown, the row keeps **`cost_usd` NULL** — never a fabricated `0` from missing rates.",
        "- **avg_evaluation_cost_per_run_usd_llm** / **_heuristic**: `AVG(cost_usd)` within that bucket over rows with **`cost_usd IS NOT NULL` only**; all-NULL in a bucket → **not available**.",
        "- **llm_judge_call_rate**: `COUNT(used_llm_judge IS TRUE) / COUNT(evaluation_results)` (all rows).",
        "- **Latency (global)**: `avg_*_latency_ms` over all runs with non-NULL column (may mix evaluators). **Split** evaluation/total latencies: `avg_*_latency_ms_llm` / `_heuristic`.",
        "- **Failure-type counts:** only rows with non-empty `failure_type` are grouped. An empty list under a bucket means **no such values in that slice**, not “zero failures” unless you also see explicit `NO_FAILURE: N` lines.",
        "",
        "### Dataset / benchmark scale",
    ]

    def line(label: str, key: str) -> None:
        v = m.get(key)
        if v is None:
            lines.append(f"- {label}: not available")
        else:
            lines.append(f"- {label}: {_fmt_num(v)}")

    if m.get("_missing_tables"):
        lines.append(
            f"- _Schema incomplete — missing tables: {', '.join(m['_missing_tables'])}_"
        )
        lines.extend(
            [
                "",
                "### Quality / evaluation",
                "- _Apply Alembic migrations and insert benchmark data, then re-run this script._",
                "",
                "### Ingestion inventory (optional)",
            ]
        )
        lines.extend(_inventory_lines(m))
        return "\n".join(lines)

    line("benchmark_datasets", "benchmark_datasets")
    line("total_queries", "total_queries")
    line("total_traced_runs", "total_traced_runs")
    line("total_traced_runs_heuristic", "total_traced_runs_heuristic")
    line("total_traced_runs_llm", "total_traced_runs_llm")
    line("evaluation_rows_heuristic", "evaluation_rows_heuristic")
    line("evaluation_rows_llm", "evaluation_rows_llm")
    line("configs_tested", "configs_tested")

    lines.extend(["", "### Performance — global (all runs, non-NULL column)"])
    for phase in ("retrieval", "generation", "evaluation", "total"):
        av = m.get(f"avg_{phase}_latency_ms")
        p95 = m.get(f"p95_{phase}_latency_ms")
        if av is None and p95 is None:
            lines.append(
                f"- avg_{phase}_latency_ms / p95_{phase}_latency_ms: not available (no measured samples)"
            )
        else:
            lines.append(
                f"- avg_{phase}_latency_ms: {_fmt_num(av)}; p95_{phase}_latency_ms: {_fmt_num(p95)}"
            )

    lines.extend(
        [
            "",
            "### Performance — by evaluator (join `runs` ↔ `evaluation_results`)",
            "- evaluation / total latency only (retrieval is identical for both paths on a given run).",
        ]
    )
    for phase in ("evaluation", "total"):
        for bucket in ("heuristic", "llm"):
            av = m.get(f"avg_{phase}_latency_ms_{bucket}")
            p95 = m.get(f"p95_{phase}_latency_ms_{bucket}")
            if av is None and p95 is None:
                lines.append(
                    f"- {phase}_latency_ms ({bucket}): not available (no measured samples)"
                )
            else:
                lines.append(
                    f"- {phase}_latency_ms ({bucket}): avg {_fmt_num(av)}; p95 {_fmt_num(p95)}"
                )

    lines.extend(["", "### Quality — LLM judge rows only (`avg_*_llm`)"])
    for col, label in (
        ("faithfulness", "average_faithfulness"),
        ("completeness", "average_completeness"),
        ("retrieval_relevance", "average_retrieval_relevance_score"),
        ("context_coverage", "average_context_coverage_score"),
        ("groundedness", "average_groundedness"),
    ):
        line(label, f"avg_{col}_llm")

    lines.extend(["", "### Quality — heuristic rows only (`avg_*_heuristic`)"])
    for col, label in (
        ("faithfulness", "average_faithfulness"),
        ("completeness", "average_completeness"),
        ("retrieval_relevance", "average_retrieval_relevance_score"),
        ("context_coverage", "average_context_coverage_score"),
        ("groundedness", "average_groundedness"),
    ):
        line(label, f"avg_{col}_heuristic")

    lines.extend(["", "### Failure types — LLM rows"])
    _failure_lines(
        lines,
        m.get("failure_type_counts_llm") or {},
        bucket_row_count=m.get("evaluation_rows_llm"),
    )

    lines.extend(["", "### Failure types — heuristic rows"])
    _failure_lines(
        lines,
        m.get("failure_type_counts_heuristic") or {},
        bucket_row_count=m.get("evaluation_rows_heuristic"),
    )

    lines.extend(["", "### Failure types — all rows (audit; do not average across evaluator)"])
    n_llm, n_h = m.get("evaluation_rows_llm"), m.get("evaluation_rows_heuristic")
    total_eval = None
    if n_llm is not None and n_h is not None:
        total_eval = int(n_llm) + int(n_h)
    _failure_lines(lines, m.get("failure_type_counts_all") or {}, bucket_row_count=total_eval)

    lines.extend(["", "### Cost / efficiency (split by evaluator bucket)"])
    line("avg_evaluation_cost_per_run_usd (llm rows only)", "avg_evaluation_cost_per_run_usd_llm")
    line(
        "avg_evaluation_cost_per_run_usd (heuristic rows only)",
        "avg_evaluation_cost_per_run_usd_heuristic",
    )
    rate = m.get("llm_judge_call_rate")
    if rate is None:
        lines.append("- llm_judge_call_rate: not available")
    else:
        lines.append(
            f"- llm_judge_call_rate (all evaluation rows): {rate:.6f}".rstrip("0").rstrip(".")
        )

    lines.extend(["", "### Ingestion inventory (optional)"])
    lines.extend(_inventory_lines(m))

    return "\n".join(lines)


def _failure_lines(
    lines: list[str],
    fcounts: dict[str, int],
    *,
    bucket_row_count: int | None = None,
) -> None:
    if bucket_row_count is not None and bucket_row_count == 0:
        lines.append("- _N/A — no evaluation rows in this slice_")
        return
    if not fcounts:
        lines.append(
            "- _no non-empty `failure_type` values in this slice (see semantics above)_"
        )
    else:
        for ft, c in sorted(fcounts.items(), key=lambda x: x[0]):
            lines.append(f"- {ft}: {c}")


def _inventory_lines(m: dict[str, Any]) -> list[str]:
    out = []
    dc, cc = m.get("document_count"), m.get("chunk_count")
    out.append(f"- documents (ingestion): {_fmt_num(dc) if dc is not None else 'not available'}")
    out.append(f"- chunks (ingestion): {_fmt_num(cc) if cc is not None else 'not available'}")
    return out


def render_text_json(m: dict[str, Any]) -> str:
    import json

    safe = {k: v for k, v in m.items() if not k.startswith("_")}
    if "_missing_tables" in m:
        safe["_missing_tables"] = m["_missing_tables"]
    return json.dumps(safe, indent=2, default=str)


async def _async_main(fmt: str) -> None:
    async with engine.connect() as conn:
        m = await aggregate_all_metrics(conn)
    if fmt == "markdown":
        print(render_project_metrics_markdown(m))
    else:
        print(render_text_json(m))


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--format", choices=("text", "markdown"), default="markdown")
    args = p.parse_args()
    asyncio.run(_async_main(args.format))


if __name__ == "__main__":
    main()
